GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/books/5c1e HTTP/1.1

###
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "Test Book"
}

####
PUT http://localhost:3001/books/4698 HTTP/1.1
Content-Type: application/json

{
  "title":"Updated Book Title"
}

###
DELETE http://localhost:3001/books/4698 HTTP/1.1